sudo: false

git:
  depth: 10
language: node_js
node_js:
- node

branches:
  only:
    - master

cache:
  directories:
    - node_modules


before_install:
  # remove outdated deps, assists with cache maintenance
  - npm prune
